[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/add-link"
  to = "/.netlify/functions/add-link"
  status = 200

[[redirects]]
  from = "/api/fetch-og"
  to = "/.netlify/functions/fetch-og"
  status = 200
